name: Lint

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  changed-files:
    name: Changed Files
    outputs:
      status: ${{ steps.changed-files.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v23.2
        with:
          files: |
            package.json
            package-lock.json
            .eslintignore
            .eslintrc.json
            phpcs.xml
            **/*.css
            **/*.js
            **/*.php

  lint:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.status == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}

      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: |
            vendor
            ~/.composer
          key: ${{ runner.os }}-build-${{ hashFiles('composer.lock') }}

      - name: Install node
        run: npm install

      - name: Install composer
        run: composer install

      - name: Lint style
        run: npm run lint-style

      - name: Lint JS
        run: npm run lint-js

      - name: Lint PHP
        run: npm run lint-php
